# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 00:25
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170917_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='+8210XXXXXXXX', max_length=128),
        ),
    ]
